# Generated by Django 5.2.7 on 2026-08-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_grandeunite_matiere_grande_unite_matiereaa"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="professeur",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Professeur"
            ),
        ),
        migrations.DeleteModel(
            name="MatiereAA",
        ),
    ]
