# Generated by Django 5.2.7 on 2026-08-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_matiere_professeur_delete_matiereaa"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="identifiant_permanent",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Identifiant Permanent (IP)",
            ),
        ),
    ]
